name: vton_bot
channels:
  - conda-forge
  - defaults
  - nvidia
dependencies:
  - _openmp_mutex=4.5
  - alsa-lib=1.2.14
  - aom=3.9.1
  - attr=2.5.1
  - blosc=1.21.6
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-blosc2=2.18.0
  - ca-certificates=2025.6.15
  - cairo=1.18.4
  - charls=2.4.2
  - colorama=0.4.6
  - cpython=3.10.18
  - cudatoolkit=11.7.1
  - dataclasses=0.8
  - dav1d=1.2.1
  - dbus=1.16.2
  - ffmpeg=7.1.1
  - filelock=3.18.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.13.3
  - fribidi=1.0.10
  - fsspec=2025.5.1
  - fvcore=0.1.5.post20221221
  - gdk-pixbuf=2.42.12
  - gettext=0.24.1
  - gettext-tools=0.24.1
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - graphite2=1.3.14
  - harfbuzz=11.2.1
  - icu=75.1
  - imagecodecs=2025.3.30
  - imageio=2.37.0
  - importlib-metadata=8.7.0
  - iopath=0.1.10
  - jinja2=3.1.6
  - jxrlib=1.1
  - kaldi=5.5.1112
  - lame=3.100
  - lazy-loader=0.4
  - lcms2=2.17
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - level-zero=1.22.5
  - libabseil=20250127.1
  - libaec=1.1.4
  - libasprintf=0.24.1
  - libasprintf-devel=0.24.1
  - libass=0.17.3
  - libavif16=1.3.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.75
  - libcblas=3.9.0
  - libde265=1.0.15
  - libdeflate=1.24
  - libdrm=2.4.125
  - libegl=1.7.0
  - libexpat=2.7.0
  - libffi=3.4.6
  - libflac=1.4.3
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgcrypt-lib=1.11.1
  - libgettextpo=0.24.1
  - libgettextpo-devel=0.24.1
  - libgfortran=15.1.0
  - libgfortran5=15.1.0
  - libgl=1.7.0
  - libglib=2.84.2
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgpg-error=1.55
  - libheif=1.19.7
  - libhwloc=2.11.2
  - libhwy=1.2.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - libjxl=0.11.1
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - liblzma=5.8.1
  - libnsl=2.0.1
  - libogg=1.3.5
  - libopenvino=2025.0.0
  - libopenvino-auto-batch-plugin=2025.0.0
  - libopenvino-auto-plugin=2025.0.0
  - libopenvino-hetero-plugin=2025.0.0
  - libopenvino-intel-cpu-plugin=2025.0.0
  - libopenvino-intel-gpu-plugin=2025.0.0
  - libopenvino-intel-npu-plugin=2025.0.0
  - libopenvino-ir-frontend=2025.0.0
  - libopenvino-onnx-frontend=2025.0.0
  - libopenvino-paddle-frontend=2025.0.0
  - libopenvino-pytorch-frontend=2025.0.0
  - libopenvino-tensorflow-frontend=2025.0.0
  - libopenvino-tensorflow-lite-frontend=2025.0.0
  - libopus=1.5.2
  - libpciaccess=0.18
  - libpng=1.6.49
  - libprotobuf=5.29.3
  - librsvg=2.58.4
  - libsndfile=1.2.2
  - libsqlite=3.50.1
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libsystemd0=257.6
  - libtiff=4.7.0
  - libtorch=2.7.1
  - libudev1=257.6
  - libunwind=1.6.2
  - liburing=2.10
  - libusb=1.0.29
  - libuuid=2.38.1
  - libuv=1.51.0
  - libva=2.22.0
  - libvorbis=1.3.7
  - libvpx=1.14.1
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.10.0
  - libxml2=2.13.8
  - libzlib=1.3.1
  - libzopfli=1.0.3
  - llvm-openmp=20.1.7
  - lz4-c=1.10.0
  - markupsafe=3.0.2
  - mkl=2024.2.2
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpg123=1.32.9
  - mpmath=1.3.0
  - ncurses=6.5
  - networkx=3.4.2
  - ocl-icd=2.3.3
  - opencl-headers=2025.06.13
  - openfst=1.8.3
  - openh264=2.6.0
  - openjpeg=2.5.3
  - openssl=3.5.0
  - optree=0.16.0
  - packaging=25.0
  - pango=1.56.3
  - pcre2=10.45
  - pillow=11.2.1
  - pip=25.1.1
  - pixman=0.46.2
  - portalocker=3.2.0
  - pthread-stubs=0.4
  - pugixml=1.15
  - pulseaudio-client=17.0
  - pybind11=2.13.6
  - pybind11-global=2.13.6
  - python=3.10.18
  - python_abi=3.10
  - pytorch=2.7.1
  - pytorch3d=0.7.7
  - pywavelets=1.8.0
  - pyyaml=6.0.2
  - rav1e=0.7.1
  - readline=8.2
  - scikit-image=0.25.2
  - scipy=1.15.2
  - sdl2=2.32.54
  - sdl3=3.2.16
  - setuptools=80.9.0
  - sleef=3.8
  - snappy=1.2.1
  - svt-av1=3.0.2
  - sympy=1.14.0
  - tabulate=0.9.0
  - tbb=2021.13.0
  - termcolor=3.1.0
  - tifffile=2025.5.10
  - tk=8.6.13
  - torchaudio=2.7.1
  - torchvision=0.22.0
  - torchvision-extra-decoders=0.0.2
  - tqdm=4.67.1
  - trimesh=4.6.12
  - typing-extensions=4.14.0
  - typing_extensions=4.14.0
  - tzdata=2025b
  - wayland=1.23.1
  - wayland-protocols=1.45
  - wheel=0.45.1
  - x264=1!164.3095
  - x265=3.5
  - xkeyboard-config=2.45
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcursor=1.2.3
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxrender=0.9.12
  - xorg-libxscrnsaver=1.2.4
  - yacs=0.1.8
  - yaml=0.2.5
  - zfp=1.0.1
  - zipp=3.23.0
  - zlib-ng=2.2.4
  - zstd=1.5.7
  - pip:
      - absl-py==2.3.0
      - aiofiles==24.1.0
      - aiogram==3.20.0.post0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.18
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - anyio==4.9.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - certifi==2025.6.15
      - cffi==1.17.1
      - charset-normalizer==3.4.2
      - coloredlogs==15.0.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - exceptiongroup==1.3.0
      - flatbuffers==25.2.10
      - fonttools==4.58.4
      - frozenlist==1.7.0
      - h11==0.16.0
      - hf-xet==1.1.4
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.33.0
      - humanfriendly==10.0
      - idna==3.10
      - iniconfig==2.1.0
      - jax==0.6.2
      - jaxlib==0.6.2
      - jsonschema==4.24.0
      - jsonschema-specifications==2025.4.1
      - kiwisolver==1.4.8
      - llvmlite==0.44.0
      - magic-filter==1.0.12
      - matplotlib==3.10.3
      - mediapipe==0.10.21
      - ml-dtypes==0.5.1
      - multidict==6.5.0
      - numba==0.61.2
      - numpy==1.26.4
      - onnxruntime==1.22.0
      - opencv-contrib-python==4.11.0.86
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.11.0.86
      - opt-einsum==3.4.0
      - platformdirs==4.3.8
      - pluggy==1.6.0
      - pooch==1.8.2
      - propcache==0.3.2
      - protobuf==4.25.8
      - psutil==7.0.0
      - pycparser==2.22
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pygments==2.19.1
      - pymatting==1.1.14
      - pyparsing==3.2.3
      - pytest==8.4.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.0
      - python-telegram-bot==22.1
      - referencing==0.36.2
      - rembg==2.0.66
      - requests==2.32.4
      - rpds-py==0.25.1
      - sentencepiece==0.2.0
      - six==1.17.0
      - smplx==0.1.28
      - sniffio==1.3.1
      - sounddevice==0.5.2
      - tomli==2.2.1
      - typing-inspection==0.4.1
      - urllib3==2.5.0
      - yarl==1.20.1
